# Generated by Django 4.2.16 on 2024-10-01 03:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('F', 'Físico'), ('J', 'Jurídico')], default='F', max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('F', 'Físico'), ('J', 'Jurídico')], default='F', max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
