# Generated by Django 4.2.16 on 2024-10-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='payments',
            new_name='payment',
        ),
    ]
