# Generated by Django 4.2.16 on 2024-10-01 16:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(default='Sales', max_length=100)),
                ('hire_date', models.DateField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
